package com.example.tools;

import java.util.List;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Component;

import com.example.entity.EmpSkillMap;
import com.example.entity.Employee;
import com.example.entity.Skill;
import com.example.service.EmployeeService;

@Component
public class EmployeeTools {

    private final EmployeeService employeeService;

    public EmployeeTools(EmployeeService employeeService) {
        this.employeeService = employeeService;
    }

    @Tool(description = """
    		Create a NEW employee record.

    		Use this tool only when the user wants to create a new employee.

    		Populate:
    		- id
    		- name
    		- address
    		""")
    public Employee addEmployee(Employee employee) {

        System.out.println("Tool Called");
        System.out.println(employee.getName()+" "+employee.getAddress());

        return employeeService.addEmployee(employee);
    }
    @Tool(description = """
    		Create a NEW skill in the database.

    		Use this tool ONLY when the user wants to create a new skill.

    		Do NOT use this tool when the user is assigning an existing skill to an employee.

    		Required fields:
    		- id
    		- name
    		""")
    public Skill createSkill(Skill skill) {

        System.out.println("Tool Called");

        return employeeService.addSkill(skill);
    }

    @Tool(description = """
    		Assign an EXISTING skill to an EXISTING employee.

    		Use this tool when the user provides an employee ID and a skill ID and rating

    		Do NOT create a new skill.
    		id is autogenerated
    		Parameters:
    		- employeeId : existing employee id
    		- skillId : existing skill id
    		- rating : skill rating from 1 to 10
    		""")    public String assignExistingSkillToEmployee(Long employeeId, long skillId, int rating) {
    	System.out.println("Adding skill "+employeeId +" "+skillId);
    	EmpSkillMap saved = employeeService.assignSkillService(employeeId, skillId,rating);

        return "Skill '"   + "' added successfully.";
    }

    @Tool(description = "Returns all employees who possess the specified skill.")
    public List<Employee> getEmployeesBySkill(String skillName) {

        return employeeService.getEmployeesBySkill(skillName);
    }

    @Tool(description = "Return all employees")
    public List<Employee> getAllEmployees() {
        return employeeService.getAllEmployees();
    }
}